creammist/biomarker/views.py
from flask import Blueprint, render_template, redirect, url_for, Response
from creammist import db
from creammist.models import Experiment, DoseResponse, JagsSampling, SensitivityScore, CellLine, Mutation, \
    GeneExpression, Gene, OmicsProfiles
from creammist.biomarker.forms import BiomarkerForm, ChoiceForm

from flask import request, send_file

from creammist.biomarker import plot_data
import pandas as pd
import json
import plotly


biomarker_blueprint = Blueprint('biomarker',
                                __name__, template_folder='templates/biomarker')


@biomarker_blueprint.route('/download/<string:drug>/<string:gene>/<string:cancer_type>', methods=['GET', 'POST'])
def download(gene, drug, cancer_type):
    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.standard_drug_name == drug,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)
    mutation_df = mutation_df[['dataset', 'statistic', 'pvalue', 'provided_statistic', 'provided_pvalue']]
    mutation_df = mutation_df.rename(
        columns={'statistic': 'creammist_effect_size_mutation', 'provided_statistic': 'original_source_effect_size_mutation',
                 'pvalue': 'creammist_pvalue_mutation', 'provided_pvalue': 'original_source_pvalue_mutation'})

    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.standard_drug_name == drug,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()
    express_df = pd.read_sql(express_data.statement, db.session.bind)
    express_df = express_df[['dataset', 'correlation', 'pvalue', 'provided_correlation', 'provided_pvalue']]
    express_df = express_df.rename(
        columns={'correlation': 'creammist_correlation_expression', 'provided_correlation': 'original_source_correlation_expression',
                 'pvalue': 'creammist_pvalue_expression', 'provided_pvalue': 'original_source_pvalue_expression'})

    df = pd.merge(mutation_df, express_df, on=['dataset'], how='outer')

    path = f'gene/output/biomarker_{gene}_{drug}_{cancer_type}_information.csv'
    df.to_csv('creammist/' + path, index=False)
    return send_file(path, as_attachment=True)


@biomarker_blueprint.route('/_autocomplete', methods=['GET'])
def autocomplete():

    gene_records = db.session.query(Gene.gene_name).all()
    gene_name_db = [r.gene_name for r in gene_records]
    return Response(json.dumps(gene_name_db), mimetype='application/json')


@biomarker_blueprint.route('/_autocomplete_drug', methods=['GET'])
def autocomplete_drug():
    gene = request.args.get('gene')
    # print(gene)
    # print(request.form.get('hidden_name'))
    drug_mutation_records = db.session.query(Mutation.standard_drug_name).filter(Mutation.gene == gene).distinct()
    drug_express_records = db.session.query(GeneExpression.standard_drug_name).filter(
        GeneExpression.gene == gene).distinct()

    drug_mutation_list = [r.standard_drug_name for r in drug_mutation_records]
    drug_express_list = [r.standard_drug_name for r in drug_express_records]

    drug_name_db = list(set(drug_mutation_list).union(set(drug_express_list)))
    # print(drug_name_db)

    # drug_name_db = [r.standard_drug_name for r in drug_records]

    return Response(json.dumps(drug_name_db), mimetype='application/json')


@biomarker_blueprint.route('/select/', methods=['GET', 'POST'])
def select():  # choose cell line
    form = BiomarkerForm()
    if request.method == 'POST':
        gene_name = request.form.get('gene_name')
        drug_name = request.form.get('drug_name')

        drug_mutation_records = db.session.query(Mutation.standard_drug_name).filter(Mutation.gene == gene_name, Mutation.standard_drug_name == drug_name).distinct()
        drug_express_records = db.session.query(GeneExpression.standard_drug_name).filter(GeneExpression.gene == gene_name,GeneExpression.standard_drug_name == drug_name).distinct()
        drug_mutation_list = [r.standard_drug_name for r in drug_mutation_records]
        drug_express_list = [r.standard_drug_name for r in drug_express_records]

        if len(drug_mutation_list)!=0 or len(drug_express_list)!=0 :
            return redirect(
            url_for('biomarker.information_biomarker', gene=gene_name, drug=drug_name, cancer_type='pancan'))
        else:
            return render_template('select_biomarker.html', form=form)
    return render_template('select_biomarker.html', form=form)


@biomarker_blueprint.route("/<string:gene>/<string:drug>/<string:cancer_type>", methods=['GET', 'POST'])
def information_biomarker(gene, drug, cancer_type):

    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.standard_drug_name == drug,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)

    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.standard_drug_name == drug,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()
    express_df = pd.read_sql(express_data.statement, db.session.bind)


    # all dataset
    mutation_records = db.session.query(Mutation).filter(Mutation.gene == gene,
                                                         Mutation.standard_drug_name == drug)  # .all()
    cancer_type_mutation_list = list(set(r.cancer_type for r in mutation_records))

    express_records = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                              GeneExpression.standard_drug_name == drug)  # .all()
    cancer_type_express_list = list(set(r.cancer_type for r in express_records))

    cancer_type_list = list(set(cancer_type_mutation_list).union(set(cancer_type_express_list)))

    # form for select dataset
    form = ChoiceForm()
    form.cancer_type.choices = [(c, c) for c in cancer_type_list]
    form.cancer_type.default = cancer_type
    form.process()

    if request.method == 'POST':
        cancer_type = request.form.get('cancer_type')
        return redirect(url_for('biomarker.information_biomarker', gene=gene, drug=drug, cancer_type=cancer_type))

    # plot graph
    fig_mutation_stat, box_plot, mut_plot = plot_data.plot_mutation(mutation_df)
    fig_express_stat, scatt_plot, exp_plot = plot_data.plot_expression(express_df)
    if mut_plot:
        graph1Jason = json.dumps(fig_mutation_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph1Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    if exp_plot:
        graph2Jason = json.dumps(fig_express_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph2Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)


    # plot information
    # find cell line match cancer type
    if cancer_type == 'pancan':
        cancer_type_records = db.session.query(CellLine.cellosaurus_id).all()
    else:
        cancer_type_records = db.session.query(CellLine.cellosaurus_id).filter(CellLine.site == cancer_type).all()
    cell_line_list = [r.cellosaurus_id for r in cancer_type_records]


    # find ic50
    data = db.session.query(CellLine, Experiment, JagsSampling) \
        .join(Experiment, Experiment.cellosaurus_id == CellLine.cellosaurus_id) \
        .join(JagsSampling, JagsSampling.exp_id == Experiment.id).filter(Experiment.standard_drug_name == drug,
                                                                         Experiment.dataset == 'All')  # .all()
    df = pd.read_sql(data.statement, db.session.bind)
    df = df[df['cellosaurus_id'].isin(cell_line_list)]
    df = df[['cellosaurus_id', 'standard_drug_name', 'beta0_mode']]


    # find mut/exp values
    mut_exp_data = db.session.query(OmicsProfiles).filter(OmicsProfiles.gene == gene)  # .all()
    mut_exp_df = pd.read_sql(mut_exp_data.statement, db.session.bind)

    mut_exp_df = mut_exp_df[mut_exp_df['cellosaurus_id'].isin(cell_line_list)]
    mut_exp_df = mut_exp_df[['cellosaurus_id', 'gene', 'values', 'score']]


    if box_plot:
        fig_box_mutation = plot_data.plot_box_mutation(df, mut_exp_df)
        graph3Jason = json.dumps(fig_box_mutation, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph3Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)


    if scatt_plot:
        fig_scatter_expression = plot_data.plot_scatter_expression(df, mut_exp_df)
        graph4Jason = json.dumps(fig_scatter_expression, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph4Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    return render_template('information_biomarker.html', data=mutation_data, graph1Jason=graph1Jason,
                           graph2Jason=graph2Jason,
                           graph3Jason=graph3Jason, graph4Jason=graph4Jason, form=form, gene=gene, drug=drug,
                           cancer_type=cancer_type)

creammist/biomarker/templates/biomarker/information_biomarker.html
{% extends "base.html" %}

{% block content %}
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <section class="py-5">
        <div class="container py-5">
            <div class="row gy-5">
                <!-- Listing-->
                <div class="col-lg-12 order-1 order-lg-2">
                    <!-- Listing sorting-->
                    <div class="card border-0 shadow-sm mb-4 mb-lg-5 p-2 p-lg-0">
                        <div class="card-body p-lg-5" id="content1">
                            <h2 class="h4 mb-4">Biomarker information </h2>
                            Drug-gene associations based on IC50 and mutation (or gene expression) profile. IC50 value was estimated using the <a href={{ url_for('doc.dose_response_curve') }}>integrated dose-response curve</a>.
                            <br><br>
                            <b>Gene :</b>
                            <a href="{{ url_for('gene.information_gene', gene=gene, dataset='All', cancer_type=cancer_type) }}">{{ gene }} </a><br>
                            <b>Drug Name :</b>
                            <a href="{{ url_for('drug.information_drug', drug=drug, dataset='All') }}">{{ drug }} </a><br>
                            <b>Cancer type :</b>
                            <a href="{{ url_for('cancer_type.information_cancer_type', dataset='All', cancer_type=cancer_type) }}">{{ cancer_type }} </a></p>
                        </div>
                    </div>

                    <div class="row gy-4">
                        <div class="col-lg-6" >
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-lg-5">
                                    <h4>Association Information </h4>
                                    <p>Click to show/hide information cards below or download drug gene association information.</p>
                                    <input class="form-check-input" type="checkbox" id="chk2" , data-ptag="content2"
                                           name="chk2" checked>
                                    <label class="form-check-label" for="chk2">Mutation</label>&nbsp;&nbsp;

                                    <input class="form-check-input" type="checkbox" id="chk3" , data-ptag="content3"
                                           name="chk3" checked>
                                    <label class="form-check-label" for="chk3">Gene Expression</label>&nbsp;<br><br>
                                    <div style="float: right;">
                                        <form action="{{ url_for('biomarker.download',gene=gene,drug=drug, cancer_type=cancer_type) }}"
                                              method="POST">
                                            <button class="btn btn-info w-10" type="submit"><i
                                                    class="fa fa-download me-2 small"></i>Data
                                            </button>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6" >
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-lg-5">
                                    <p>Information cards below will change according to the cancer type selected.</p>
                                    <form action="{{ url_for('biomarker.information_biomarker',gene=gene, drug=drug,cancer_type=cancer_type) }}"
                                          method="POST">
                                        <b>{{ form.cancer_type.label }} :</b> &nbsp;&nbsp; {{ form.cancer_type(class="btn btn-light bg-white shadow-xs border text-start align-items-center")}} <br><br>

                                        <button class="btn btn-primary w-10" type="submit"><i
                                                class="fas fa-search me-2 small"></i>Search
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div><br>


                    <!-- Listing items-->

                    <div class="row mb-4 gy-4">
                        <!-- Gallery-->
                        <div class="col-lg-6" id="content2">
                            <h2 class="h4 mb-4">Drug-gene association (IC50 vs mutation)</h2>
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4" >
                                    <p>Ranksum’s effect size was calculated by comparing IC50 between mutant and wide-type cell lines <a href={{ url_for('doc.biomarker') }}>(more detail)</a>.</p>
                                    <div id="chart1">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6" id="content3">
                            <h2 class="h4 mb-4">Drug-gene association (IC50 vs gene expression)</h2>
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4" >
                                    <p>Spearman correlation was calculated by comparing IC50 and gene expression (TMM) across cell lines <a href={{ url_for('doc.biomarker') }}>(more detail)</a>.</p>
                                    <div id="chart2">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <h2 class="h4 mb-4">IC50 vs mutation</h2>
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4" >
                                    <p>Relationships between IC50 and mutation profiles base on "All" dataset.</p>
                                    <div id="chart3">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <h2 class="h4 mb-4">IC50 vs gene expression</h2>

                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4">
                                    <p>Relationships between IC50 and gene expression profiles base on "All" dataset.</p>
                                    <div id="chart4">
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://cdn.plot.ly/plotly-1.58.5.min.js"></script>
    <script type="text/javascript">
        var graph1 = {{ graph1Jason | safe}};
        graph1.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart1', graph1, {})


        var graph2 = {{ graph2Jason | safe}};
        graph2.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart2', graph2, {})

        var graph3 = {{ graph3Jason | safe}};
        graph3.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart3', graph3, {})

        var graph4 = {{ graph4Jason | safe}};
        graph4.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart4', graph4, {})

    </script>


    <!-- #### for show/hide div -->

    <script type="text/javascript">
        var first = true;
        $('input[type="checkbox"][name^=chk]').change(function () {
            var $target = $('#content' + this.id.replace('chk', '')).toggle(this.checked);
            if (first) {
                $('p[id^=content]').not($target).hide();
                first = false;
            }
        })
    </script>

{% endblock %}

creammist/biomarker/templates/biomarker/select_biomarker.html
{% extends "base.html" %}

{% block content %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table/jquery-ui.css')}}">-->

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!--    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}-->

    <style>
        .ui-autocomplete {
            max-height: 320px;
            overflow: scroll;
            background-color: #fcdce7;
            overflow-y: scroll;
            scrollbar-color: #D6B2A7;
            scrollbar-width: thin;
        }
    </style>

    <section class="hero-home py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-7 mx-auto text-center">
                    <p class="h6 text-uppercase text-primary mb-3">BIOMARKER</p>
                    <h2 class="mb-5">Search by Gene and Drug Name</h2>
                    <form class="p-2 rounded shadow-sm bg-white" action="{{ url_for('biomarker.select') }}"
                          method="POST">
<!--                        {#                        <div class="input-group">#}-->
                        {{ form.gene_name(class="form-control border-1 me-2 shadow-0",placeholder="(Gene Name) Example: ICAM3") }}
                        <br>
                        {{ form.drug_name(class="form-control border-1 me-2 shadow-0",placeholder="(Drug Name) Example: Bortezomib") }}
                        <br>
                        <button class="btn btn-primary rounded" type="submit"><i class="fas fa-search"></i></button>
<!--                        {#                        </div>#}-->
                        <script>
                            $(function () {
                                $.ajax({
                                    url: '{{ url_for("biomarker.autocomplete") }}'
                                }).done(function (data) {
                                    $('#biomarker_autocomplete').autocomplete({
                                        source: data,
                                        minLength: 2
                                    });
                                });
                            });
                        </script>
                        <script>
                            var gene_select = document.getElementById('biomarker_autocomplete');
                            {#var hidden_value = document.getElementById('hidden').value;#}

                            gene_select.onchange = function () {
                                console.log(gene_select.value);
                                $.ajax({
                                    url: '{{ url_for("biomarker.autocomplete_drug") }}' + '?gene=' + gene_select.value,

                                }).done(function (data) {
                                    $('#biomarker_autocomplete_drug').autocomplete({
                                        source: data,
                                        minLength: 1
                                    });
                                });
                            }
                        </script>
                    </form>
                    <br>
                    <span style="float:left;">Examples:
                        <a href="#" id="link-id1">ICAM3+Bortezomib</a> -
                        <a href="#" id="link-id2">EGFR+EphB4_9721</a> -
                        <a href="#" id="link-id3">EGFR+Lapatinib</a>
                    </span>
                </div>
            </div>
        </div>
    </section>



<script type="text/javascript">
    $(function () {
        $("#link-id1").click(function () {
            $('#biomarker_autocomplete').val('ICAM3');
            $('#biomarker_autocomplete').submit();

            $('#biomarker_autocomplete_drug').val('Bortezomib');
            $('#biomarker_autocomplete_drug').submit();
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $("#link-id2").click(function () {
            $('#biomarker_autocomplete').val('EGFR');
            $('#biomarker_autocomplete').submit();

            $('#biomarker_autocomplete_drug').val('EphB4_9721');
            $('#biomarker_autocomplete_drug').submit();
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function () {
        $("#link-id3").click(function () {
            $('#biomarker_autocomplete').val('EGFR');
            $('#biomarker_autocomplete').submit();

            $('#biomarker_autocomplete_drug').val('Lapatinib');
            $('#biomarker_autocomplete_drug').submit();
            return false;
        });
    });
</script>

{% endblock %}