creammist/doc/views.py
from flask import Blueprint, render_template, redirect, url_for, Response


from flask import request, send_file


doc_blueprint = Blueprint('doc',
                          __name__, template_folder='templates/doc')


@doc_blueprint.route('/information/', methods=['GET', 'POST'])
def information():
    return render_template('overall_doc.html')


@doc_blueprint.route('/cell_line/', methods=['GET', 'POST'])
def cell_line():
    return render_template('cell_line_doc.html')


@doc_blueprint.route('/drug/', methods=['GET', 'POST'])
def drug():
    return render_template('drug_doc.html')


@doc_blueprint.route('/cancer_type/', methods=['GET', 'POST'])
def cancer_type():
    return render_template('cancer_type_doc.html')


@doc_blueprint.route('/gene/', methods=['GET', 'POST'])
def gene():
    return render_template('gene_doc.html')


@doc_blueprint.route('/biomarker/', methods=['GET', 'POST'])
def biomarker():
    return render_template('biomarker_doc.html')

@doc_blueprint.route('/dose_response_curve/', methods=['GET', 'POST'])
def dose_response_curve():
    return render_template('dose_response_curve_doc.html')

@doc_blueprint.route('/bulk_download/', methods=['GET', 'POST'])
def download_bulk():
    path = f'doc/bulk_download/bulk_download.csv'
    return send_file(path, as_attachment=True)


@doc_blueprint.route('/bulk/', methods=['GET', 'POST'])
def bulk():
    return render_template('bulk_doc.html')

creammist/doc/templates/doc/base_doc.html
{% extends "base.html" %}

{% block content %}

    <section class="py-5">
        <div class="container py-5">
            <div class="row gy-5">
                <div class="col-lg-3 order-2 order-lg-1">
                    {#                    <h2 class="h3 mb-4 pb-1">Filter</h2>#}
                    <div class="card border-0 shadow-sm mb-4 p-2">
                        <div class="card-body">
                            <h2 class="h5 mb-4">Topics</h2>
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.dose_response_curve') }}>A dose-response curve</a>
                                </li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.information') }}>Data statistics</a>
                                </li>
                                <br>

                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.cell_line') }}>Query by cell line </a>
                                </li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.drug') }}>Query by drug</a></li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.cancer_type') }}>Query by cancer type</a></li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.gene') }}>Query by gene</a></li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('doc.biomarker') }}>Query by drug and gene</a>
                                </li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                    href={{ url_for('api.information') }}>API</a>
                                </li>
                                <br>
                                <li class="list-inline-item "><a class="btn btn-light"
                                                                 href={{ url_for('doc.bulk') }}>Bulk download</a>
                                </li>
                                <br>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Listing-->
                <div class="col-lg-9 order-2 order-lg-1">
                    {% block doc_content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </section>





{% endblock %}

creammist/doc/templates/doc/biomarker_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Select gene and drug </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/b_1.png') }} alt="..."
                         width="450">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Drug-gene associations based on IC50 and mutation (or gene expression) profile </span></h2>
        Racksum’s effect size was calculated by comparing IC50 between the mutant and wide-type cell lines. Mutant cell lines are those that have at least one mutation (allele frequency >= 0.2) in a given gene.
        Spearman correlation was calculated by comparing IC50 and gene expression (TMM).
        The association scores were calculated only for gene-drug pairs with at least 10 wild-type and 10 mutant cell lines, or with at least 10 cell lines for gene expression. We discard dose gene drug pair with an absolute correlation value less than 0.2. The association scores based on IC50 provided by the original source are also provided (yellow dot)
       Each (unadjusted) p-value was calculated for each pair of drug and gene independently.<br><br>


        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/b_2.png') }} alt="..."
                         width="900"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/b_3.png') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>





{% endblock %}

creammist/doc/templates/doc/bulk_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

<div class=" mb-4 p-2" id="content1">
    <h2 class="h4 mb-4"><span style="color:#17a2b8"> Download integrative dose-response information </span></h2>
    <div class="card shadow-sm border-0">
        <div class="card-body p-4">
            <form action="{{ url_for('doc.download_bulk') }}"
                  method="POST">
                <button class="btn btn-info w-10" type="submit"><i
                        class="fa fa-download me-2 small"></i> Download
                </button>
            </form><br>

            <table class="table table-bordered" style="border-radius: 5px 5px 5px 5px;">
                <thead>
                <tr>
                    <th>Column name</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>cellosaurus_id</td>
                    <td>Cell line ID according to Cellosaurus</td>
                </tr>
                <tr>
                    <td>drug_name</td>
                    <td>Drug name</td>
                </tr>
                <tr>
                    <td>dataset </td>
                    <td>"All" means all available datasets for a given drug-cell line pair</td>
                </tr>
                <tr>
                    <td>original_datasets </td>
                    <td>A list of original datasets</td>
                </tr>
                <tr>
                    <td>n_dosage </td>
                    <td>Number of testing concentrations</td>
                </tr>
                <tr>
                    <td>min_dosage </td>
                    <td>Minimum concentration (uM)</td>
                </tr>
                <tr>
                    <td>max_dosage </td>
                    <td>Maximum concentration (uM)</td>
                </tr>
                <tr>
                    <td> fitted_mae</td>
                    <td>Mean absolute error of the integrative dose-response curve</td>
                </tr>
                <tr>
                    <td>slope </td>
                    <td>A slope of the integrative dose-response curve</td>
                </tr>
                <tr>
                    <td>IC50_HDI_low </td>
                    <td>A lower end of high density interval (95%) of IC50</td>
                </tr>
                <tr>
                    <td> IC50_HDI_high</td>
                    <td>A higher end of high density interval (95%) of IC50</td>
                </tr>
                <tr>
                    <td>IC50 </td>
                    <td>Drug concentration needed to inhibit the cells by 50%</td>
                </tr>
                <tr>
                    <td>IC90 </td>
                    <td>Drug concentration needed to inhibit the cells by 90%</td>
                </tr>
                <tr>
                    <td>EC50 </td>
                    <td>Half-maximal effective dosage</td>
                </tr>
                <tr>
                    <td> Einf</td>
                    <td>Response at the highest drug dosage tested</td>
                </tr>
                <tr>
                    <td> AUC</td>
                    <td>Area under the integrative dose-response curve</td>
                </tr>
                </tbody>
            </table>
            <i>Last update: September 2022.
            The file includes 1,325 cell lines, 1,132 drugs and 829,782 drug-cell line pairs.</i>
<!--            cellosaurus_id, drug_name, dataset, original_datasets, n_dosage, min_dosage, max_dosage, fitted_mae, slope, IC50_HDI_low,-->
<!--            IC50_HDI_high, IC50, IC90, EC50, Einf, AUC-->

<!--            <div style="float: right;">-->
<!--                <form action="{{ url_for('doc.download_bulk') }}"-->
<!--                      method="POST">-->
<!--                    <button class="btn btn-info w-10" type="submit"><i-->
<!--                            class="fa fa-download me-2 small"></i> Download-->
<!--                    </button>-->
<!--                </form>-->
<!--            </div>-->
        </div>

    </div>
</div>
<!--<div class=" mb-4 p-2" id="content2">-->
<!--&lt;!&ndash;    <h2 class="h4 mb-4"><span style="color:#17a2b8"> .... </span></h2>&ndash;&gt;-->
<!--&lt;!&ndash;    .....<br><br>&ndash;&gt;-->

<!--    <div class="card shadow-sm border-0">-->
<!--        <div class="card-body p-4">-->
<!--            <div class="card-body p-4">-->
<!--                <img class="img-fluid" src={{ url_for('static', filename='img/doc/bulk.png') }} alt="..."-->
<!--                width="900"><br><br>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->





{% endblock %}

creammist/doc/templates/doc/cancer_type_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Select cancer type </span></h2>
        Search or browse cancer types <br><br>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cct_1.png') }} alt="..."
                         width="450">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Drug response information </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cct_2.png') }} alt="..."
                         width="200"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cct_3.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cct_4.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cct_5.png') }} alt="..."
                         width="400">
                </div>
            </div>
        </div>
    </div>





{% endblock %}

creammist/doc/templates/doc/cell_line_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Select cell line name </span></h2>
        Search or browse cell lines <br><br>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_1.png') }} alt="..."
                         width="450">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Cell line information </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_2.png') }} alt="..."
                         width="270"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_3.png') }} alt="..."
                         width="1000">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_4.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_5.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_6.png') }} alt="..."
                         width="400">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content3">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Experimental information of a given cell line and drug </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_7.png') }} alt="..."
                         width="400"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_8.png') }} alt="..."
                         width="570">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_9.png') }} alt="..."
                         width="250">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_10.png') }} alt="..."
                         width="350">
                </div>
            </div>
        </div>
    </div>




{% endblock %}

creammist/doc/templates/doc/dose_response_curve_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}
<!--math equation-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css" integrity="sha384-zB1R0rpPzHqg7Kpt0Aljp8JPLqbXI3bhnPWROx27a9N0Ll6ZP/+DiW/UqRcLbRjq" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js" integrity="sha384-y23I5Q6l+B6vatafAwxRu/0oK/79VlbSz7Q9aiSZUvyWYIYsd+qj+o24G5ZU2zJz" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js" integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script>


<div class=" mb-4 p-2" id="content1">
    <h2 class="h4 mb-4"><span style="color:#17a2b8"> Experimental information </span></h2>
    For the dose-response relationship, each dot indicates drug response at different dosages, and each color represents the original datasets. A pink line is an integrated dose-response curve. Grey lines represent alternative dose-response curves resulting from a Bayesian curve fitting. A horizontal dashed line represents 50% cell inhibitions. A vertical dashed line represents IC50.  <br><br>
    <div class="card shadow-sm border-0">
        <div class="card-body p-4">
            <div class="card-body p-4">
                <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_7.png') }} alt="..."
                width="400"><br><br>
                <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_8.png') }} alt="..."
                width="570">
                <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_9.png') }} alt="..."
                width="250">
                <img class="img-fluid" src={{ url_for('static', filename='img/doc/cl_10.png') }} alt="..."
                width="350">
            </div>
        </div>
    </div>
    <br>

    <span style="color: #28a745"><b>IC50</b></span>  indicates drug concentration needed to inhibit the cells by 50%, <i>in vitro</i>, compared to the control well.<br>
    <span style="color: #28a745"><b>IC90</b></span>  indicates drug concentration needed to inhibit the cells by 90%, <i>in vitro</i>, compared to the control well.<br>
        <span style="color: #28a745"><b>AUC</b></span>  represents the area under a dose-response curve, where 0% indicates no activity and 100% indicates that a drug completely inhibits the cells across testing dosages.<br>
            <span style="color: #28a745"><b>EC50</b></span>  indicates half-maximal effective dosage, which induces a response halfway between the baseline and maximum inhibition.<br>
                <span style="color: #28a745"><b>Einf</b></span>  indicates the response at the highest drug dosage tested.<br>



</div>
<div class=" mb-4 p-2" id="content2">
    <h2 class="h4 mb-4"><span style="color:#17a2b8"> Dose-response curve fitting </span></h2>
    <div class="card shadow-sm border-0">
        <div class="card-body p-4">
            <div class="card-body p-4">
                <h5>Obtaining response information at different dosages</h5>
                <ul class="fa-ul">
                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>CCLE</li>
                    dosage = dosage <br>
                    response = response &#215; -0.01<br><br>
                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>GDSC 1 and 2</li>
                    neg control = NC-0 <br>
                    pos control = B <br>

                    dosage = conc <br>
                    response = (neg_val-intensity) &#247; (neg_val-pos_val)<br><br>

                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>CTRP 1 and 2</li>
                    dosage = cpd_conc_umol<br>
                    response = 1- cpd_avg_pv

                </ul>
                <br>

                <!-- (B) TEX EQUATION -->

                <h5>A Bayesian curve fitting</h5>
                <ul class="fa-ul">
                    <li><span class="fa-li"><i class="fas fa-marker" style="color:#6c757d"></i></span>Logistic equation and parameter description</li>
                    \[f(x) = \displaystyle\frac{1}{1+2^{-k(x-a)}}\]

                    <li><span class="fa-li"><i class="fas fa-marker" style="color:#6c757d"></i></span>
                        We used <a href="https://mcmc-jags.sourceforge.io/">JAGS</a> to estimate a dose-response curve for each cell line. Initial parameters:</li>
                    <br>
                    <table class="table table-bordered" style="border-radius: 5px 5px 5px 5px;">
                        <thead>
                        <tr>
                            <th>Parameter</th>
                            <th>Value</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>n_iter</td>
                            <td>5000</td>
                            <td>Number of samplings</td>
                        </tr>
                        <tr>
                            <td>burn_in</td>
                            <td>500</td>
                            <td>Burn in samplings</td>
                        </tr>
                        <tr>
                            <td>n_chain </td>
                            <td>3</td>
                            <td>Number of chains</td>
                        </tr>
                        <tr>
                            <td>k </td>
                            <td>dgamma(k_r, k_lambda)</td>
                            <td rowspan="3" style="vertical-align: middle">A gamma distribution of slope</td>
                        </tr>
                        <tr>
                            <td>k_lambda </td>
                            <td>dnorm(2 , 0.01)</td>
                        </tr>
                        <tr>
                            <td>k_r </td>
                            <td>dnorm(1 , 0.01)</td>
                        </tr>
                        <tr>
                            <td>a </td>
                            <td>dnorm(a_mu , \((\frac{1}{a\_sigma})^2\) )</td>
                            <td rowspan="3" style="vertical-align: middle">A normal distribution of location (IC50)</td>
                        </tr>
                        <tr>
                            <td>a_mu </td>
                            <td>dnorm(0 , 1)</td>
                        </tr>
                        <tr>
                            <td>a_sigma </td>
                            <td>dunif(0.01 , 5)</td>
                        </tr>

                        <tr>
                            <td>f(x) </td>
                            <td>dt( \(\frac{1}{1+2^{-k(x-a)}}\) , \((\frac{1}{sigma})^2\) , nu)</td>
                            <td rowspan="3" style="vertical-align: middle"> A student's t-distribution of dose response curve fitting</td>
                        </tr>
                        <tr>
                            <td>nu </td>
                            <td>dnorm(250 , 0.001)</td>
                        </tr>
                        <tr>
                            <td>sigma </td>
                            <td>dunif(0.01 , 0.1)</td>
                        </tr>

                        </tbody>
                    </table>
                </ul>

            </div>
        </div>
    </div>
</div>


{% endblock %}

creammist/doc/templates/doc/drug_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Select drug name </span></h2>
        Search or browse drugs <br><br>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_1.png') }} alt="..."
                         width="450">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Drug information </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_2.png') }} alt="..."
                         width="270"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_3.png') }} alt="..."
                         width="1000">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_4.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_5.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_6.png') }} alt="..."
                         width="400"><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_7.png') }} alt="..."
                         width="400">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_8.png') }} alt="..."
                         width="400">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content3">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Experimental information of a given cell line and drug </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_9.png') }} alt="..."
                         width="320"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_10.png') }} alt="..."
                         width="600">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_11.png') }} alt="..."
                         width="220">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_12.png') }} alt="..."
                         width="350">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content4">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Associated genes </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_13.png') }} alt="..."
                         width="900"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/d_14.png') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>




{% endblock %}

creammist/doc/templates/doc/gene_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Select gene </span></h2>
        Search or browse genes <br><br>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/g_1.png') }} alt="..."
                         width="450">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Gene information </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/g_2.png') }} alt="..."
                         width="150"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/g_3.png') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content3">
        <h2 class="h4 mb-4"><span style="color:#17a2b8"> Associated drugs </span></h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/g_4.png') }} alt="..."
                         width="900"><br><br>
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/g_5.png') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>




{% endblock %}

creammist/doc/templates/doc/overall_doc.html
{% extends "base_doc.html" %}

{% block doc_content %}

    <div class=" mb-4 p-2" id="content1">
        <h2 class="h4 mb-4"> Cell line statistics</h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/number_cellline.svg') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>
    <div class=" mb-4 p-2" id="content2">
        <h2 class="h4 mb-4"> Drug statistics</h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <img class="img-fluid" src={{ url_for('static', filename='img/doc/number_drug.svg') }} alt="..."
                         width="1000">
                </div>
            </div>
        </div>
    </div>

    <div class=" mb-4 p-2" id="content3">
        <h2 class="h4 mb-4"> Drug response data sources</h2>
        <div class="card shadow-sm border-0">
            <div class="card-body p-4">
                <div class="card-body p-4">
                    <table class="table table-bordered" style="border-radius: 5px 5px 5px 5px;">
                        <thead>
                        <tr>
                            <th>Data source name</th>
                            <th>Version</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>CCLE</td>
                            <td>20 Febuary 2012 (CCLE_NP24.2009_profiling_2012.02.20)</td>
                        </tr>
                        <tr>
                            <td>CTRP1</td>
                            <td>2013 (CTRPv1.0_2013_pub_Cell_154_1151)</td>
                        </tr>
                        <tr>
                            <td>CTRP2 </td>
                            <td>2015 (CTRPv2.0_2015_ctd2_ExpandedDataset)</td>
                        </tr>
                        <tr>
                            <td>GDSC1 </td>
                            <td>24 July 2022 (GDSC1_public_raw_data_24Jul22)</td>
                        </tr>
                        <tr>
                            <td>GDSC2 </td>
                            <td>24 July 2022 (GDSC2_public_raw_data_24Jul22)</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}