creammist/api/views.py
from flask import Blueprint, render_template
from creammist import db
from creammist.models import Experiment, DoseResponse, JagsSampling, SensitivityScore, CellLine, OmicsProfiles, Drug, \
    Gene, GeneExpression, Mutation

from flask import jsonify
import pandas as pd
import json


api_blueprint = Blueprint('api',
                          __name__, template_folder='templates/api')


@api_blueprint.route('/information/', methods=['GET', 'POST'])
def information():
    return render_template('information_api.html')


@api_blueprint.route('/celllines', methods=['GET'])
def get_all_celllines_data():
    data = db.session.query(CellLine)
    df = pd.read_sql(data.statement, db.session.bind)
    result = df.to_json(orient="records")
    return result


@api_blueprint.route('/celllines/<string:cell_line>', methods=['GET'])
def get_drug_with_cl_info(cell_line):
    data = db.session.query(Experiment).filter(Experiment.cellosaurus_id == cell_line)
    df = pd.read_sql(data.statement, db.session.bind)
    df = df[['cellosaurus_id', 'standard_drug_name', 'dataset', 'info']]
    df = df.rename(columns={'standard_drug_name':'drug_name','info':'original_datasets'})
    if df.shape[0] > 0:
        result = df.to_json(orient="records")
        return result, 200
    else:
        return jsonify({"message": "404 Not Found"}), 404


@api_blueprint.route('/cancertypes', methods=['GET'])
def get_all_cancertypes_data():
    data = db.session.query(CellLine.site).distinct()
    df = pd.read_sql(data.statement, db.session.bind)
    df.loc[len(df.index)] = 'pancan'
    df = df[df['site'] != '']
    result = json.dumps({"cancer_types": list(df['site'])})  # df.to_json(orient="values")
    return result


@api_blueprint.route('/cancertypes/<string:cancer_type>', methods=['GET'])
def get_cl_with_cancertypes(cancer_type):
    if cancer_type == 'pancan':
        data = db.session.query(CellLine.cellosaurus_id)
    else:
        data = db.session.query(CellLine.cellosaurus_id).filter(CellLine.site == cancer_type)
    df = pd.read_sql(data.statement, db.session.bind)
    if df.shape[0] > 0:
        result = json.dumps({"cell_lines": list(df['cellosaurus_id'])})
        return result, 200
    else:
        return jsonify({"message": "404 Not Found"}), 404


@api_blueprint.route('/experiments/<string:cell_line>/<string:drug>', methods=['GET'])
def get_experiments(cell_line, drug):
    data = db.session.query(Experiment, JagsSampling, SensitivityScore) \
        .join(JagsSampling, JagsSampling.exp_id == Experiment.id) \
        .join(SensitivityScore, SensitivityScore.exp_id == Experiment.id).filter(Experiment.cellosaurus_id == cell_line,
                                                                                 Experiment.standard_drug_name == drug)  # .all()

    df = pd.read_sql(data.statement, db.session.bind)

    exp_id_list = list(df[df['dataset'] != 'All']['exp_id'])

    list_of_dose_list = []

    for _, row in df.iterrows():
        if row['dataset'] == 'All':
            dose_list = db.session.query(DoseResponse).filter(DoseResponse.exp_id.in_(exp_id_list)).all()
        else:
            dose_list = DoseResponse.query.filter_by(exp_id=row['exp_id']).all()
        list_of_dose_list += [[(d.dosage, d.response) for d in dose_list]]
    df.loc[:, 'dose_response'] = list_of_dose_list

    df = df[['cellosaurus_id', 'standard_drug_name', 'dataset', 'info', 'n_dosage', 'min_dosage', 'max_dosage',
             'dose_response','fitted_mae','beta1_mode', 'beta0_HDI_low','beta0_HDI_high', 'ic50_mode', 'ic90_calculate', 'ec50_calculate',
             'einf_calculate', 'auc_calculate',]]
    # print(df)
    df = df.rename(columns={'ic50_mode': 'IC50', 'ic90_calculate': 'IC90', 'ec50_calculate': 'EC50',
                            'einf_calculate': 'Einf', 'auc_calculate': 'AUC','standard_drug_name':'drug_name',
                            'info':'original_datasets','beta1_mode':'slope','beta0_HDI_low':'IC50_HDI_low','beta0_HDI_high':'IC50_HDI_high'})
    result = df.to_json(orient="records")
    return result


@api_blueprint.route('/drugs', methods=['GET'])
def get_all_drug_data():
    data = db.session.query(Drug)
    df = pd.read_sql(data.statement, db.session.bind)
    df = df.rename(columns={'standard_drug_name':'drug_name'})
    result = df.to_json(orient="records")
    return result


@api_blueprint.route('/drugs/<string:drug>', methods=['GET'])
def get_cl_with_drug_info(drug):
    data = db.session.query(Experiment).filter(Experiment.standard_drug_name == drug)  # .all()
    df = pd.read_sql(data.statement, db.session.bind)
    df = df[['standard_drug_name', 'cellosaurus_id', 'dataset', 'info']]
    df = df.rename(columns={'standard_drug_name':'drug_name','info':'original_datasets'})

    if df.shape[0] > 0:
        result = df.to_json(orient="records")
        return result, 200
    else:
        return jsonify({"message": "404 Not Found"}), 404


@api_blueprint.route('/genes', methods=['GET'])
def get_all_genes_data():
    data = db.session.query(Gene).distinct()
    df = pd.read_sql(data.statement, db.session.bind)
    result = json.dumps({'genes': list(df['gene_name'])})  # df.to_json(orient="values")
    return result


@api_blueprint.route(
    '/biomarker/<string:exp_mut>/<string:cancer_type>/gene/<string:gene>/<string:pos_neg>/<string:n_top>',
    methods=['GET'])
def get_gene_express_mut(exp_mut, cancer_type, gene, pos_neg, n_top):
    if exp_mut == 'exp':
        express_data = db.session.query(GeneExpression).filter(GeneExpression.cancer_type == cancer_type,
                                                               GeneExpression.gene == gene,
                                                               GeneExpression.dataset == 'All')  # .all()
        df = pd.read_sql(express_data.statement, db.session.bind)
        df = df[['standard_drug_name', 'gene', 'dataset', 'cancer_type', 'correlation', 'pvalue', 'n_cell_line']]
        df = df.rename(columns={'standard_drug_name':'drug_name'})

        if pos_neg == 'pos':
            df = df[df['correlation'] >= 0].sort_values(by='correlation', ascending=False).head(int(n_top))
        elif pos_neg == 'neg':
            df = df[df['correlation'] <= 0].sort_values(by='correlation', ascending=True).head(int(n_top))

        if df.shape[0] > 0:
            result = df.to_json(orient="records")
            return result, 200
        else:
            return jsonify({"message": "404 Not Found"}), 404

    elif exp_mut == 'mut':
        mutation_data = db.session.query(Mutation).filter(Mutation.cancer_type == cancer_type, Mutation.gene == gene,
                                                          Mutation.dataset == 'All')  # .all()
        df = pd.read_sql(mutation_data.statement, db.session.bind)
        df = df.rename(columns={'statistic': 'effect_size', 'provided_statistic': 'provided_effect_size'})
        df = df[['standard_drug_name', 'gene', 'dataset', 'cancer_type', 'effect_size', 'pvalue', 'n_mut', 'n_wt']]
        df = df.rename(columns={'standard_drug_name':'drug_name'})

        if pos_neg == 'pos':
            df = df[df['effect_size'] >= 0].sort_values(by='effect_size', ascending=False).head(int(n_top))
        elif pos_neg == 'neg':
            df = df[df['effect_size'] <= 0].sort_values(by='effect_size', ascending=True).head(int(n_top))

        if df.shape[0] > 0:
            result = df.to_json(orient="records")
            return result, 200
        else:
            return jsonify({"message": "404 Not Found"}), 404


@api_blueprint.route(
    '/biomarker/<string:exp_mut>/<string:cancer_type>/drug/<string:drug>/<string:pos_neg>/<string:n_top>',
    methods=['GET'])
def get_drug_express_mut(exp_mut, cancer_type, drug, pos_neg, n_top):
    if exp_mut == 'exp':
        express_data = db.session.query(GeneExpression).filter(GeneExpression.cancer_type == cancer_type,
                                                               GeneExpression.standard_drug_name == drug,
                                                               GeneExpression.dataset == 'All')  # .all()
        df = pd.read_sql(express_data.statement, db.session.bind)
        df = df[['standard_drug_name', 'gene', 'dataset', 'cancer_type', 'correlation', 'pvalue', 'n_cell_line']]
        df = df.rename(columns={'standard_drug_name':'drug_name'})

        if pos_neg == 'pos':
            df = df[df['correlation'] >= 0].sort_values(by='correlation', ascending=False).head(int(n_top))
        elif pos_neg == 'neg':
            df = df[df['correlation'] <= 0].sort_values(by='correlation', ascending=True).head(int(n_top))

        if df.shape[0] > 0:
            result = df.to_json(orient="records")
            return result, 200
        else:
            return jsonify({"message": "404 Not Found"}), 404

    elif exp_mut == 'mut':
        mutation_data = db.session.query(Mutation).filter(Mutation.cancer_type == cancer_type,
                                                          Mutation.standard_drug_name == drug,
                                                          Mutation.dataset == 'All')  # .all()
        df = pd.read_sql(mutation_data.statement, db.session.bind)
        df = df.rename(columns={'statistic': 'effect_size', 'provided_statistic': 'provided_effect_size'})
        df = df[['standard_drug_name', 'gene', 'dataset', 'cancer_type', 'effect_size', 'pvalue', 'n_mut', 'n_wt']]
        df = df.rename(columns={'standard_drug_name':'drug_name'})

        if pos_neg == 'pos':
            df = df[df['effect_size'] >= 0].sort_values(by='effect_size', ascending=False).head(int(n_top))
        elif pos_neg == 'neg':
            df = df[df['effect_size'] <= 0].sort_values(by='effect_size', ascending=True).head(int(n_top))

        if df.shape[0] > 0:
            result = df.to_json(orient="records")
            return result, 200
        else:
            return jsonify({"message": "404 Not Found"}), 404

creammist/doc/views.py
from flask import Blueprint, render_template, redirect, url_for, Response


from flask import request, send_file


doc_blueprint = Blueprint('doc',
                          __name__, template_folder='templates/doc')


@doc_blueprint.route('/information/', methods=['GET', 'POST'])
def information():
    return render_template('overall_doc.html')


@doc_blueprint.route('/cell_line/', methods=['GET', 'POST'])
def cell_line():
    return render_template('cell_line_doc.html')


@doc_blueprint.route('/drug/', methods=['GET', 'POST'])
def drug():
    return render_template('drug_doc.html')


@doc_blueprint.route('/cancer_type/', methods=['GET', 'POST'])
def cancer_type():
    return render_template('cancer_type_doc.html')


@doc_blueprint.route('/gene/', methods=['GET', 'POST'])
def gene():
    return render_template('gene_doc.html')


@doc_blueprint.route('/biomarker/', methods=['GET', 'POST'])
def biomarker():
    return render_template('biomarker_doc.html')

@doc_blueprint.route('/dose_response_curve/', methods=['GET', 'POST'])
def dose_response_curve():
    return render_template('dose_response_curve_doc.html')

@doc_blueprint.route('/bulk_download/', methods=['GET', 'POST'])
def download_bulk():
    path = f'doc/bulk_download/bulk_download.csv'
    return send_file(path, as_attachment=True)


@doc_blueprint.route('/bulk/', methods=['GET', 'POST'])
def bulk():
    return render_template('bulk_doc.html')

creammist/gene/views.py
from flask import Blueprint, render_template, redirect, url_for, Response
from creammist import db
from creammist.models import Experiment, DoseResponse, JagsSampling, SensitivityScore, CellLine, Mutation, \
    GeneExpression, Gene
from creammist.gene.forms import GeneForm, ChoiceForm

from flask import request, send_file


from creammist.gene import plot_data

import pandas as pd
import json
import plotly

gene_blueprint = Blueprint('gene',
                           __name__, template_folder='templates/gene')


@gene_blueprint.route('/download_mutation/<string:dataset>/<string:gene>/<string:cancer_type>', methods=['GET', 'POST'])
def download_mutation(gene, dataset, cancer_type):
    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.dataset == dataset,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)

    mutation_df = mutation_df[
        ['gene', 'standard_drug_name', 'dataset', 'cancer_type', 'statistic', 'pvalue', 'n_mut', 'n_wt']]
    mutation_df = mutation_df.rename(columns={'statistic': 'effect_size','standard_drug_name':'drug_name'})
    path = f'gene/output/mutation_{gene}_{cancer_type}_{dataset}_information.csv'
    mutation_df.to_csv('creammist/' + path, index=False)
    return send_file(path, as_attachment=True)


@gene_blueprint.route('/download_expression/<string:dataset>/<string:gene>/<string:cancer_type>',
                      methods=['GET', 'POST'])
def download_expression(gene, dataset, cancer_type):
    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.dataset == dataset,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()
    express_df = pd.read_sql(express_data.statement, db.session.bind)

    express_df = express_df[
        ['gene', 'standard_drug_name', 'dataset', 'cancer_type', 'correlation', 'pvalue', 'n_cell_line']]
    express_df = express_df.rename(columns={'standard_drug_name':'drug_name'})

    path = f'gene/output/gene_expression_{gene}_{cancer_type}_{dataset}_information.csv'
    express_df.to_csv('creammist/' + path, index=False)
    return send_file(path, as_attachment=True)


@gene_blueprint.route('/_autocomplete', methods=['GET'])
def autocomplete():
    gene_records = db.session.query(Gene.gene_name).all()
    gene_name_db = [r.gene_name for r in gene_records]

    return Response(json.dumps(gene_name_db), mimetype='application/json')


@gene_blueprint.route('/select/', methods=['GET', 'POST'])
def select():
    gene_records = db.session.query(Gene.gene_name).all()
    gene_name_db = [r.gene_name for r in gene_records]

    form = GeneForm()
    if request.method == 'POST':
        gene = request.form.get('name')
        if gene in gene_name_db:
            return redirect(url_for('gene.information_gene', gene=gene, dataset='All', cancer_type='pancan'))
        else:
            return render_template('select_gene.html', form=form,data=gene_name_db)
    return render_template('select_gene.html', form=form,data=gene_name_db)


@gene_blueprint.route("/<string:dataset>/<string:gene>/<string:cancer_type>", methods=['GET', 'POST'])
def information_gene(gene, dataset, cancer_type):  # show information cell line

    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.dataset == dataset,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.dataset == dataset,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()

    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)
    express_df = pd.read_sql(express_data.statement, db.session.bind)
    # print(mutation_df.shape)

    # all dataset
    gene_mutation_records = db.session.query(Mutation).filter(Mutation.gene == gene)  # .all()
    dataset_mutation_list = list(set(r.dataset for r in gene_mutation_records))
    cancer_type_mutation_list = list(set(r.cancer_type for r in gene_mutation_records))

    gene_exprees_records = db.session.query(GeneExpression).filter(GeneExpression.gene == gene)  # .all()
    dataset_exprees_list = list(set(r.dataset for r in gene_exprees_records))
    cancer_type_express_list = list(set(r.cancer_type for r in gene_exprees_records))

    dataset_list = sorted(list(set(dataset_mutation_list).union(set(dataset_exprees_list))))
    cancer_type_list = sorted(list(set(cancer_type_mutation_list).union(set(cancer_type_express_list))))

    #check nodata?
    if len(dataset_list)==0 or len(cancer_type_list)==0:
        nodata = True
    else:
        nodata = False


    # form for select dataset
    form = ChoiceForm()
    form.dataset.choices = [(d, d) for d in dataset_list]
    form.cancer_type.choices = [(c, c) for c in cancer_type_list]

    form.dataset.default = dataset
    form.cancer_type.default = cancer_type
    form.process()

    if request.method == 'POST':
        dataset = request.form.get('dataset')
        cancer_type = request.form.get('cancer_type')
        # score = request.form.get('score')
        return redirect(url_for('gene.information_gene', gene=gene, dataset=dataset, cancer_type=cancer_type))

    # plot graph
    if mutation_df.shape[0] > 0:
        fig_mutation_stat = plot_data.plot_statistic(mutation_df, 'statistic')
        graph1Jason = json.dumps(fig_mutation_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph1Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    if express_df.shape[0] > 0:
        fig_express_stat = plot_data.plot_statistic(express_df, 'correlation')
        graph2Jason = json.dumps(fig_express_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph2Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    return render_template('information_gene.html', data=mutation_data, form=form, graph1Jason=graph1Jason,
                           graph2Jason=graph2Jason,
                           gene=gene, dataset=dataset, cancer_type=cancer_type,nodata=nodata)

creammist/templates/index.html
{% extends "base.html" %}

{% block content %}

    <section class="hero-home py-5">
        <div class="container pt-5">

            <div class="row">
                <div class="col-lg-7 mx-auto text-center">
                    <p class="h6 text-uppercase text-primary mb-3">DATABASE</p>
                    <h1 class="mb-5">CREAMMIST</h1>
                </div>



                <div class="container pb-5 col-lg-12 mx-auto text-center">
                    <div class="row text-center gy-4">
                        <div class="col-lg-2 px-lg-2">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/cell_line.jpg') }}" alt="" width="50"  style="margin-bottom: 10px">
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('cell_line.select') }}>Cell Line</a></h2>
                                    <p class="categories-item-number small mb-0">1,325 cell lines</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 px-lg-1">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/drug.jpg') }}" alt="" width="50" style="margin-bottom: 10px">
<!--                                    <div class="essential-tool-img mb-2 mx-auto" style="background: url('static/img/drug.jpg'); width: auto"></div>-->
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('drug.select') }}>Drug</a></h2>
                                    <p class="categories-item-number small mb-0">1,132 drugs</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 px-lg-1">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/cc_type.jpg') }}" alt="" width="50" style="margin-bottom: 10px">
                                    <!--                                    <div class="essential-tool-img mb-2 mx-auto" style="background: url('static/img/gene.jpg'); width: auto"></div>-->
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('cancer_type.select') }}>Cancer Type</a></h2>
                                    <p class="categories-item-number small mb-0">31 types</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 px-lg-1">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/gene.jpg') }}" alt="" width="50" style="margin-bottom: 10px">
<!--                                    <div class="essential-tool-img mb-2 mx-auto" style="background: url('static/img/cc_type.jpg'); width: auto"></div>-->
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('gene.select') }}>Gene</a></h2>
                                    <p class="categories-item-number small mb-0">37,602 genes</p>
                                </div>
                            </div>
                        </div>


                        <div class="col-lg-2 px-lg-1">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/biomarker.jpg') }}" alt="" width="50" style="margin-bottom: 10px">
<!--                                    <div class="essential-tool-img mb-2 mx-auto" style="background: url('static/img/biomarker.jpg'); width: auto"></div>-->
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('biomarker.select') }}>Biomarker</a></h2>
                                    <p class="categories-item-number small mb-0">30+ millions drug-gene associations</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-2 px-lg-1">
                            <div class="card border-2 shadow h-100 hover-transition">
                                <div class="card-body px-4 py-4">
                                    <img src="{{ url_for('static', filename='img/api.jpg') }}" alt="" width="50" style="margin-bottom: 10px">
<!--                                    <div class="essential-tool-img mb-2 mx-auto" style="background: url('static/img/api.jpg'); width: auto"></div>-->
                                    <h2 class="h5"><a class="stretched-link reset-anchor"
                                                      href={{ url_for('api.information') }}>API</a></h2>
                                    <p class="categories-item-number small mb-0">Integrative drug response info</p>
<!--                                    <p class="categories-item-number small mb-0">> ... drug-gene pairs</p>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <div class="container py-5">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <div class="card border-0 shadow">
                    <div class="card-body p-4 p-lg-5">
                        <div class="row gy-4">
                            <div class="col-lg-5">
                                <img src="{{ url_for('static', filename='img/index.gif') }}" alt="" width="100%" >
                                <!--                                <h2 class="h5">Gather your info</h2>-->
                                <!--                                <p class="text-muted text-sm mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>-->
                            </div>

                            <div class="col-lg-7">
                                <h2 class="h5">Reveal integrative dose-response information</h2>
                                <br>
                                <ul class="fa-ul">
                                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>CREAMMIST is an integrated cancer drug sensitivity database for <i>in vitro </i> pharmacogenomics analysis, providing an integrative dose-response curve across five widely used cancer cell-line drug-response datasets (CCLE, GDSC1, GDSC2, CTRP1, CTRP2).</li>
                                    <br>
                                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>Dose-response values are systematically integrated using the Bayesian framework to obtain an integrative dose-response curve.</li>
                                    <br>
                                    <li><span class="fa-li"><i class="fas fa-cube" style="color:#6c757d"></i></span>Users can utilize easy-to-use statistics for various downstream analyses such as identifying biomarkers, selecting drug concentrations for their experiments, or training a more robust machine learning model.</li>
                                </ul>

<!--                                <p>CREAMMIST is an integrated cancer drug sensitivity database for <i>in vitro </i> pharmacogenomics analysis, providing an integrative dose-response curve across <a href={{ url_for('doc.information') }}><u style="color: black">five widely used cancer cell-line drug-response datasets (CCLE, GDSC1, GDSC2, CTRP1, CTRP2)</u></a>. <br><br>-->
<!--                                    Users can utilize easy-to-use statistics for various downstream analyses such as identifying biomarkers, selecting drug concentrations for their experiments, or training a more robust machine learning model.</p>-->
<!--                                <p>CREAMMIST enables users to obtain an integrated dose-response across <a href={{ url_for('doc.information') }}><u style="color: black">five widely used cancer cell-line drug-response datasets</u></a>. We utilized the <a href={{ url_for('doc.dose_response_curve') }}><u style="color: black">Bayesian framework </u></a> to systematically integrate all available dose-response values across datasets. The integration at the dose-response level provides an extended view of the dose-response curve to users, especially when different ranges of drug dosages were used across experiments. Users can utilize easy-to-use statistics derived from integrative dose-response curves for various downstream analyses (such as identifying biomarkers, selecting dose range for their experiment, and training a machine learning model).</p>-->
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<div class="container pb-5">
    <header class="text-center mb-5">
        <h5><a class="nav-link" href={{ url_for('doc.dose_response_curve') }}>See the documentation to learn more </a></h5>
    </header>
</div>
</section>

{% endblock %}