creammist/gene/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, SelectField, FloatField


class GeneForm(FlaskForm):
    name = StringField('Gene :', id='gene_autocomplete')
    # drug_name = StringField('Standard drug name :', id='biomarker_autocomplete_drug')


class ChoiceForm(FlaskForm):
    score = SelectField('Select score', choices=['mutation', 'gene expression'])
    dataset = SelectField('Dataset', choices=[])
    cancer_type = SelectField('Cancer Type', choices=[])
    # submit = SubmitField('Enter')

creammist/gene/views.py
from flask import Blueprint, render_template, redirect, url_for, Response
from creammist import db
from creammist.models import Experiment, DoseResponse, JagsSampling, SensitivityScore, CellLine, Mutation, \
    GeneExpression, Gene
from creammist.gene.forms import GeneForm, ChoiceForm

from flask import request, send_file


from creammist.gene import plot_data

import pandas as pd
import json
import plotly

gene_blueprint = Blueprint('gene',
                           __name__, template_folder='templates/gene')


@gene_blueprint.route('/download_mutation/<string:dataset>/<string:gene>/<string:cancer_type>', methods=['GET', 'POST'])
def download_mutation(gene, dataset, cancer_type):
    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.dataset == dataset,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)

    mutation_df = mutation_df[
        ['gene', 'standard_drug_name', 'dataset', 'cancer_type', 'statistic', 'pvalue', 'n_mut', 'n_wt']]
    mutation_df = mutation_df.rename(columns={'statistic': 'effect_size','standard_drug_name':'drug_name'})
    path = f'gene/output/mutation_{gene}_{cancer_type}_{dataset}_information.csv'
    mutation_df.to_csv('creammist/' + path, index=False)
    return send_file(path, as_attachment=True)


@gene_blueprint.route('/download_expression/<string:dataset>/<string:gene>/<string:cancer_type>',
                      methods=['GET', 'POST'])
def download_expression(gene, dataset, cancer_type):
    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.dataset == dataset,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()
    express_df = pd.read_sql(express_data.statement, db.session.bind)

    express_df = express_df[
        ['gene', 'standard_drug_name', 'dataset', 'cancer_type', 'correlation', 'pvalue', 'n_cell_line']]
    express_df = express_df.rename(columns={'standard_drug_name':'drug_name'})

    path = f'gene/output/gene_expression_{gene}_{cancer_type}_{dataset}_information.csv'
    express_df.to_csv('creammist/' + path, index=False)
    return send_file(path, as_attachment=True)


@gene_blueprint.route('/_autocomplete', methods=['GET'])
def autocomplete():
    gene_records = db.session.query(Gene.gene_name).all()
    gene_name_db = [r.gene_name for r in gene_records]

    return Response(json.dumps(gene_name_db), mimetype='application/json')


@gene_blueprint.route('/select/', methods=['GET', 'POST'])
def select():
    gene_records = db.session.query(Gene.gene_name).all()
    gene_name_db = [r.gene_name for r in gene_records]

    form = GeneForm()
    if request.method == 'POST':
        gene = request.form.get('name')
        if gene in gene_name_db:
            return redirect(url_for('gene.information_gene', gene=gene, dataset='All', cancer_type='pancan'))
        else:
            return render_template('select_gene.html', form=form,data=gene_name_db)
    return render_template('select_gene.html', form=form,data=gene_name_db)


@gene_blueprint.route("/<string:dataset>/<string:gene>/<string:cancer_type>", methods=['GET', 'POST'])
def information_gene(gene, dataset, cancer_type):  # show information cell line

    mutation_data = db.session.query(Mutation).filter(Mutation.gene == gene, Mutation.dataset == dataset,
                                                      Mutation.cancer_type == cancer_type)  # .all()
    express_data = db.session.query(GeneExpression).filter(GeneExpression.gene == gene,
                                                           GeneExpression.dataset == dataset,
                                                           GeneExpression.cancer_type == cancer_type)  # .all()

    mutation_df = pd.read_sql(mutation_data.statement, db.session.bind)
    express_df = pd.read_sql(express_data.statement, db.session.bind)
    # print(mutation_df.shape)

    # all dataset
    gene_mutation_records = db.session.query(Mutation).filter(Mutation.gene == gene)  # .all()
    dataset_mutation_list = list(set(r.dataset for r in gene_mutation_records))
    cancer_type_mutation_list = list(set(r.cancer_type for r in gene_mutation_records))

    gene_exprees_records = db.session.query(GeneExpression).filter(GeneExpression.gene == gene)  # .all()
    dataset_exprees_list = list(set(r.dataset for r in gene_exprees_records))
    cancer_type_express_list = list(set(r.cancer_type for r in gene_exprees_records))

    dataset_list = sorted(list(set(dataset_mutation_list).union(set(dataset_exprees_list))))
    cancer_type_list = sorted(list(set(cancer_type_mutation_list).union(set(cancer_type_express_list))))

    #check nodata?
    if len(dataset_list)==0 or len(cancer_type_list)==0:
        nodata = True
    else:
        nodata = False


    # form for select dataset
    form = ChoiceForm()
    form.dataset.choices = [(d, d) for d in dataset_list]
    form.cancer_type.choices = [(c, c) for c in cancer_type_list]

    form.dataset.default = dataset
    form.cancer_type.default = cancer_type
    form.process()

    if request.method == 'POST':
        dataset = request.form.get('dataset')
        cancer_type = request.form.get('cancer_type')
        # score = request.form.get('score')
        return redirect(url_for('gene.information_gene', gene=gene, dataset=dataset, cancer_type=cancer_type))

    # plot graph
    if mutation_df.shape[0] > 0:
        fig_mutation_stat = plot_data.plot_statistic(mutation_df, 'statistic')
        graph1Jason = json.dumps(fig_mutation_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph1Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    if express_df.shape[0] > 0:
        fig_express_stat = plot_data.plot_statistic(express_df, 'correlation')
        graph2Jason = json.dumps(fig_express_stat, cls=plotly.utils.PlotlyJSONEncoder)
    else:
        graph2Jason = json.dumps(plot_data.plot_nodata(), cls=plotly.utils.PlotlyJSONEncoder)

    return render_template('information_gene.html', data=mutation_data, form=form, graph1Jason=graph1Jason,
                           graph2Jason=graph2Jason,
                           gene=gene, dataset=dataset, cancer_type=cancer_type,nodata=nodata)

creammist/gene/templates/gene/information_gene.html
{% extends "base.html" %}

{% block content %}
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">#}
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {#    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>#}
    {#    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>#}

    <section class="py-5">
        <div class="container py-5">
            <div class="row gy-5">
                <!-- Listing-->
                <div class="col-lg-12 order-1 order-lg-2">
                    <div class="card border-0 shadow-sm mb-4 mb-lg-5 p-2 p-lg-0">
                        <div class="card-body p-lg-5" id="content1">
                            <h2 class="h4 mb-4">Gene :
                                <mark style="background: #ffc107">{{ gene }} </mark>
                            </h2>
                            <b> Gene :</b> <a
                                href="{{ url_for('gene.information_gene', gene=gene, dataset='All', cancer_type=cancer_type) }}">{{ gene }} </a><br>
                            <b>Dataset :</b> {{ dataset }}<br>
                            <b>Cancer type :</b> <a
                                href="{{ url_for('cancer_type.information_cancer_type', dataset='All', cancer_type=cancer_type) }}">{{ cancer_type }} </a>
                        </div>
                    </div>

                    <div class="row gy-4">
                        <div class="col-lg-6" >
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-lg-5">
                                    <h4>Association Information </h4>
                                    <p>Click to show/hide information cards below or download the experimental information.</p>
                                    <input class="form-check-input" type="checkbox" id="chk2" , data-ptag="content2"
                                           name="chk2" checked>
                                    <label class="form-check-label" for="chk2">Associated Drugs (Mutation)</label>&nbsp;&nbsp;

                                    <input class="form-check-input" type="checkbox" id="chk3" , data-ptag="content3"
                                           name="chk3" checked>
                                    <label class="form-check-label" for="chk3">Associated Drugs (Gene Expression)</label>&nbsp;<br><br>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6" >
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-lg-5">
                                    <p>Information cards below will change according to the selected dataset and cancer type. The default dataset is “All”, which means information in the cards is based on the integration. If “All” is not selected, information cards will contain drug response information preprocessed for each dataset independently.</p>
                                    <form action="{{ url_for('gene.information_gene',gene=gene, dataset=dataset,cancer_type=cancer_type) }}"
                                          method="POST">
                                        <b>{{ form.dataset.label }} :</b> {{ form.dataset(class="btn btn-light bg-white shadow-xs border text-start  align-items-center")}} <br><br>
                                        <b>{{ form.cancer_type.label }} :</b>&nbsp; {{ form.cancer_type(class="btn btn-light bg-white shadow-xs border text-start align-items-center" )}} <br><br>
                                        {% if  nodata==True %}
                                        <button class="btn btn-primary w-10" type="submit" disabled><i
                                                class="fas fa-search me-2 small"></i>Search
                                        </button>
                                        {% else %}
                                        <button class="btn btn-primary w-10" type="submit"><i
                                                class="fas fa-search me-2 small"></i>Search
                                        </button>
                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>
                    <!-- Listing sorting-->

                    <!-- Listing items-->

                    <div class="row mb-4 gy-4">
                        <!-- Gallery-->
                        <div class="col-lg-6" id="content2">
                            <h2 class="h4 mb-4">Associated Drugs (Mutation)</h2>
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4">
                                    Drugs with the largest and lowest Ranksum’s effect sizes, calculated by comparing IC50 between the mutant and wide type cell lines using cell lines from <a
                                        href="{{ url_for('cancer_type.information_cancer_type', dataset='All', cancer_type=cancer_type) }}">{{ cancer_type }} </a>
                                    <div id="chart1">
                                        <div style="float: right;">
                                            <form action="{{ url_for('gene.download_mutation',gene=gene, dataset=dataset, cancer_type=cancer_type) }}"
                                                  method="POST">
                                                <button class="btn btn-info w-10" type="submit"><i
                                                        class="fa fa-download me-2 small"></i>Data
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6" id="content3">
                            <h2 class="h4 mb-4">Associated Drugs (Gene Expression)</h2>
                            <div class="card shadow-sm border-0 ">
                                <div class="card-body p-4">
                                    Drugs with the highest and lowest Spearman correlations, calculated by comparing gene expression and IC50 across cell lines from <a
                                        href="{{ url_for('cancer_type.information_cancer_type', dataset='All', cancer_type=cancer_type) }}">{{ cancer_type }} </a>
                                    <div id="chart2">
                                        <div style="float: right;">
                                            <form action="{{ url_for('gene.download_expression',gene=gene, dataset=dataset, cancer_type=cancer_type) }}"
                                                  method="POST">
                                                <button class="btn btn-info w-10" type="submit"><i
                                                        class="fa fa-download me-2 small"></i>Data
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </section>

    <script src="https://cdn.plot.ly/plotly-1.44.2.min.js"></script>
    <script type="text/javascript">
        var graph1 = {{ graph1Jason | safe}};
        graph1.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart1', graph1, {})

        var graph2 = {{ graph2Jason | safe}};
        graph2.config = {
            'displaylogo': false,
            'toImageButtonOptions': {
                'format': 'svg',
                'filename': 'custom_image',
                'height': 500,
                'width': 700,
                'scale': 1
            },
            'responsive': true
        }
        Plotly.plot('chart2', graph2, {})

    </script>


    <!-- #### for show/hide div -->

    <script type="text/javascript">
        var first = true;
        $('input[type="checkbox"][name^=chk]').change(function () {
            var $target = $('#content' + this.id.replace('chk', '')).toggle(this.checked);
            if (first) {
                $('p[id^=content]').not($target).hide();
                first = false;
            }
        })
    </script>





{% endblock %}

creammist/gene/templates/gene/select_gene.html
{% extends "base.html" %}

{% block content %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table/jquery-ui.css')}}">-->


    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<!--    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}-->

    <style>
        .ui-autocomplete {
            max-height: 320px;
            overflow: scroll;
            background-color: #fcdce7;
            overflow-y: scroll;
            scrollbar-color: #D6B2A7;
            scrollbar-width: thin;
        }
    </style>

    <section class="hero-home py-5">
        <div class="container pt-5">
            <div class="row">
                <div class="col-lg-7 mx-auto text-center">
                    <p class="h6 text-uppercase text-primary mb-3">GENE</p>
                    <h2 class="mb-5">Search by Gene</h2>
                    <form class="p-2 rounded shadow-sm bg-white" action="{{ url_for('gene.select') }}" method="POST">
                        <div class="input-group">
                            {{ form.name(class="form-control border-0 me-2 shadow-0",placeholder="Example: EGFR") }}
                            <br>

                            <button class="btn btn-primary rounded" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                        <script>
                            $(function () {
                                $.ajax({
                                    url: '{{ url_for("gene.autocomplete") }}'
                                }).done(function (data) {
                                    $('#gene_autocomplete').autocomplete({
                                        source: data,
                                        minLength: 2
                                    });
                                });
                            });
                        </script>
                    </form>
                    <br>
                    <span style="float:left;">Examples:
                        <a href="#" id="link-id1">EGFR</a> -
                        <a href="#" id="link-id2">ICAM3</a> -
                        <a href="#" id="link-id3">BAAT</a> -
                        <a href="#" id="link-id4">CHAD</a>
                    </span>
                </div>
            </div>
        </div>
        <div class="container py-5">
            <div class="row ">
                <div class="col-lg-10 mx-auto">
                    <div class="card border-0 shadow">
                        <div class="card-body p-4 p-lg-5">
                            <div class="row gy-4">
                                <h5>Browse Genes</h5>
                                <p>Click on gene name to query associated drugs information.</p>


                                <table id="example" class="display" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th> Gene</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for g in data %}
                                    <tr>
                                        <td>
                                            <a href="{{ url_for('gene.information_gene', gene=g, dataset='All', cancer_type='pancan') }}">{{ g }} </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>





<script type="text/javascript">
    $(function(){
        $("#link-id1").click(function(){
            $('#gene_autocomplete').val($(this).html());
            $('#gene_autocomplete').submit();
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function(){
        $("#link-id2").click(function(){
            $('#gene_autocomplete').val($(this).html());
            $('#gene_autocomplete').submit();
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function(){
        $("#link-id3").click(function(){
            $('#gene_autocomplete').val($(this).html());
            $('#gene_autocomplete').submit();
            return false;
        });
    });
</script>
<script type="text/javascript">
    $(function(){
        $("#link-id4").click(function(){
            $('#gene_autocomplete').val($(this).html());
            $('#gene_autocomplete').submit();
            return false;
        });
    });
</script>

<!--- for table -->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table/datatables.min.css')}}">
<script src="{{ url_for('static', filename='table/datatables.min.js')}}"></script>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='table/dataTables.alphabetSearch.css')}}">
<script src="{{ url_for('static', filename='table/dataTables.alphabetSearch.min.js')}}"></script>

<script>
    $(document).ready(function () {
        var table = $('#example').DataTable({
            dom: 'Alfrtip',
            alphabetSearch: {
                column: 0
            }
        });
    });
</script>

{% endblock %}